server:
  port: ${PORT:0}

spring:
  application:
    name: fn-oauth

eureka:
  client:
    service-url:
      defaultZone: http://fn-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}