server:
  port: ${PORT:0}
  
spring:
  application:
    name: fn-payroll

eureka:
  client:
    service-url:
      defaultZone: http://fn-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 2000